# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tinyRuntime-ffn',
                'doc_host': 'https://njlabo.github.io',
                'git_url': 'https://github.com/njlabo/tinyRuntime-ffn',
                'lib_path': 'tinyRuntime_ffn'},
  'syms': {'tinyRuntime_ffn.core': {'tinyRuntime_ffn.core.foo': ('core.html#foo', 'tinyRuntime_ffn/core.py')}}}
