name: benchmark
# Run the workflow if C files are modified
on:
  push:
#     paths:
#       - '**/*.c'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark-linux:
    name: Benchmark on x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libatlas-base-dev libdnnl-dev
          lscpu
          git clone https://github.com/flame/blis.git
          cd blis
          ./configure -t openmp auto
          make -j
          sudo make install
          sudo ldconfig

      - name: Prepare test environment
        run: |
          make compile BLAS=ON
          git clone --branch 1.x https://huggingface.co/datasets/ninjalabo/imagenette2-320 data
          git clone https://huggingface.co/ninjalabo/resnet18 && cp resnet18/model.pkl .
          wget https://raw.githubusercontent.com/ninjalabo/inferences/main/run.py
          python -m pip install --upgrade pip
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install toml psutil huggingface_hub fastai fasterai

      - name: Download benchmark.csv
        run: |
          wget https://raw.githubusercontent.com/ninjalabo/ninjalabo.github.io/main/benchmark.csv

      - name: Run benchmark # Save results to benchmark.csv
        run: |
          python benchmark.py

      - name: Upload benchmark-linux
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-x86
          path: benchmark.csv

# FIX: Disable ARM benchmark until ARM compute libraries are available on oneDNN
#   benchmark-mac:
#     name: Benchmark on ARM
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.9

#       - name: Dependencies
#         id: depends
#         run: |
#           brew update
#           brew install blis llvm libomp
#           export PATH="/usr/local/opt/llvm/bin:$PATH"

#       - name: Prepare test environment
#         run: |
#           make compile BLAS=ON
#           git clone --branch 1.x https://huggingface.co/datasets/ninjalabo/imagenette2-320 data
#           git clone https://huggingface.co/ninjalabo/resnet18 && cp resnet18/model.pkl .
#           wget https://raw.githubusercontent.com/ninjalabo/inferences/main/run.py
#           python -m pip install --upgrade pip
#           pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
#           pip install toml psutil huggingface_hub fastai fasterai

#       - name: Download benchmark.csv
#         run: |
#           wget https://raw.githubusercontent.com/ninjalabo/ninjalabo.github.io/main/benchmark.csv

#       - name: Run benchmark # Save results to benchmark.csv
#         run: |
#           python benchmark.py

#       - name: Upload benchmark-mac
#         uses: actions/upload-artifact@v4
#         with:
#           name: benchmark-arm
#           path: benchmark.csv

  benchmark-combine:
    name: Push Final Benchmark Results
    runs-on: ubuntu-latest
    needs: benchmark-linux #, benchmark-mac]
    steps:
      - uses: actions/checkout@v4

      # Download benchmark.csv from benchmark-linux that contains new x86 results
      - name: Download benchmark-x86
        uses: actions/download-artifact@v4
        with:
          name: benchmark-x86
          path: x86

#       # Download benchmark.csv from benchmark-mac that contains new ARM results
#       - name: Download benchmark-arm
#         uses: actions/download-artifact@v4
#         with:
#           name: benchmark-arm
#           path: arm

      - name: Download benchmark.csv
        run: |
          wget https://raw.githubusercontent.com/ninjalabo/ninjalabo.github.io/main/benchmark.csv

      - name: Combine benchmark results
        run: |
          cat x86/benchmark.csv | tail -n +2 >> benchmark.csv
#           cat arm/benchmark.csv | tail -n +2 >> x86/benchmark.csv

      - name: Pushes the output file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_WORKFLOW_TOKEN }}
        with:
          source_file: 'benchmark.csv'
          destination_repo: 'ninjalabo/ninjalabo.github.io'
          destination_branch: 'main'
          user_email: "action@github.com"
          user_name: "GitHub Action"
          commit_message: 'update benchmark.csv'
